### ISSUE TITLE
Get Involved Page

### ISSUE THREAD

**Issue by LukaszDoubleU** [we-dance/platform-v3#114]
https://wedance.vip/get-involved

Tasks:
- [ ] Create page in Figma with matching Tailwind components
- [ ] Copy content from original page to recreated page
- [ ] List of organisms, molecules and atoms in Spreadsheet
- [ ] Style components (check if someone is already owning the component)
- [ ] Add missing components

**Comment by YanaKozlovska** [comment]
List with molecules in Get Involved:
- Navigation menu
- Heading 2 + description
- Link + description
- CTA (title + description + "Join in Slack" button)
