### ISSUE TITLE
Match atoms in City Page with Tailwind

### ISSUE THREAD

**Issue by LukaszDoubleU** [we-dance/platform-v3#122]
https://wedance.vip/Munich

Create pairs such us:

Navigation Menu - Navigation/Navbars (a whole page in Figma file with navigation menus)

**Comment by JamesRobey12** [comment]
- Elements headers 
- Elements Avatars 
- Elements Buttons 
- Elements Dropdowns
- Layout dividers
- Layout Media Objectives
- Overlays/Modals
-Navigation/Navbars

**Comment by JamesRobey12** [comment]
-Forms/sign-in and registration

**Comment by JamesRobey12** [comment]
https://cottony-meadow-190.notion.site/Matching-with-Tailwind-city-page-37152bb33bf9493ba2756ed4552dd4be

**Comment by razbakov** [comment]
move to #77
