### ISSUE TITLE
Match atoms in Event View with Tailwind

### ISSUE THREAD

**Issue by LukaszDoubleU** [we-dance/platform-v3#123]
https://wedance.vip/events/c11jI5FHkYmL4pHXSmci

Create pairs such us:

Navigation Menu - Navigation/Navbars (a whole page in Figma file with navigation menus)

**Comment by Dipalidp** [comment]
Side Navigation - Application Shells/Sidebar Layouts
Event Title - Headings/Card Headings
Event Card - Layout/Media Objects (somewhat similar)
Person Card - Headings/Card Headings
Comment section - Unavailable but can be created with input fields and button atoms
