### ISSUE TITLE
Match molecules in Find Your City with Tailwind

### ISSUE THREAD

**Issue by LukaszDoubleU** [we-dance/platform-v3#124]
https://wedance.vip/cities/

![image](https://user-images.githubusercontent.com/119410857/207019170-bb16894c-13d8-4c4f-9453-8ec0c9bf055f.png)

Create pairs such us:

Navigation Menu - Navigation/Navbars (a whole page in Figma file with navigation menus)

**Comment by razbakov** [comment]
Move to #76
