### ISSUE TITLE
Competitor Analysis of Dance Festival Calendars for dancers

### ISSUE THREAD

**Issue by ZiyueSun** [we-dance/platform-v3#222]
At WeDance, we are committed to providing a seamless and convenient experience for our users.

With the existing event calendar, we wanted to provide a better user experience and in a way make our platform's events more attractive to users to get more people involved in our EVENTS.

**Comment by ZiyueSun** [comment]
Here is the new version of the competitive analysis after I correct the competitors.
https://spring-guan-878.notion.site/Competitive-analysis-of-Dance-Festival-calendars-for-dancers-6298afa453c04f2ea9f646d9172bbe72

**Comment by razbakov** [comment]
Please don't duplicate issues. This task is already tracked by #145
