### ISSUE TITLE
Categorical colors

### ISSUE THREAD

**Issue by LukaszDoubleU** [we-dance/platform-v3#68]
- [ ] Find and match categorical colors chosen previously with existing Tailwind palette
- [ ] Write in comment which one is matching which

**Comment by LukaszDoubleU** [comment]
@diazmariaelena @Dipalidp 

now we need pairs, ie:

Chinese Black (previous) - Gray 900 (Tailwind)

**Comment by Dipalidp** [comment]
Sure but if we finalise the colours first maybe this is be easier?

**Comment by Dipalidp** [comment]
@LukaszDoubleU @diazmariaelena I thought we are not using the previous colours and only matching tailwind colours 
 eg: 
Primary red (brand colour) - Not in Tailwind 
Neutral - Gray 100
Accent - Light blue 400
Success - Green 500
Warning - Yellow 300
Danger - Orange 400

But unless we finalise the colours pairing/matching is hard

**Comment by diazmariaelena** [comment]
Our semantic colors (from previous color palette) are finally added to the tailwind library's color. The list is in the same order as in figma :)

GRAY (gray 500)=                               Neutral
RED (red 500)=                                    Primary
ORANGE (orange 500)=                    Danger
YELLOW (yellow-500)=                     Warning
GREEN EMERALD (green-500)=     Success
BLUE (blue-500)=                               Accent
INDIGO (indigo-500)=                        Secondary
PURPLE VIOLET (purple-500)=       Tertiary

@LukaszDoubleU I'm sorry I didn't add the category colors cause I got all confused about what those are!

**Comment by diazmariaelena** [comment]
Hi! @LukaszDoubleU
Our semantic colors (from previous color palette) are finally added to the tailwind library's color. The list is in the same order as in figma :)

GRAY (gray 500)= Neutral
RED (red 500)= Primary
ORANGE (orange 500)= Danger
YELLOW (yellow-500)= Warning
GREEN EMERALD (green-500)= Success
BLUE (blue-500)= Accent
INDIGO (indigo-500)= Secondary
PURPLE VIOLET (purple-500)= Tertiary

 I'm sorry I didn't add the category colors cause I got all confused about what those are :/
