### ISSUE TITLE
Semantic colors

### ISSUE THREAD

**Issue by LukaszDoubleU** [we-dance/platform-v3#69]
- [x] Find and match semantic colors chosen previously with existing Tailwind palette
- [x] Write in comment which one is matching which

**Comment by Dipalidp** [comment]
@LukaszDoubleU 
https://www.figma.com/file/PHz4M2L9BKtWiWi7SbNPQh/dark-theme-colors-team-library?node-id=411%3A2&t=gRlFFH8wmmd2PRXY-1
Here are the semantic colors we chose yesterday.
Is there anything else you want me to do/add?

**Comment by Dipalidp** [comment]
Hard to pair until all colours are finalised

**Comment by Dipalidp** [comment]
@LukaszDoubleU @razbakov @diazmariaelena  this is my work on semantic colours so far:
https://www.figma.com/file/PHz4M2L9BKtWiWi7SbNPQh/Color-System-playground?node-id=411%3A2&t=V342wmSwp0vYHSMP-3

As mentioned by Aleksey, Maria handing over to you. Thanks

**Comment by diazmariaelena** [comment]
Hello! @LukaszDoubleU I added our semantic colors to Tailwind's library. The list is in the same order as in figma! 
( I need to clarify about categorical colors!) 

Gray (Cool gray)-500= Neutral
 Red-500 = Primary
Orange-500= Danger
 Yellow Amber-500=Warning 
 Green (Emerald)-500= Success
  Blue-500= Accent
   Indigo-500= Secondary
    Purple (Violet)-500=Tertiary
