### ISSUE TITLE
Atoms in City Page

### ISSUE THREAD

**Issue by LukaszDoubleU** [we-dance/platform-v3#72]
Identify & list atoms in https://wedance.vip/Munich

**Comment by YanaKozlovska** [comment]
List of atoms in the City page:
- Navigation menu
- "Find a location" button
- "Search" button
- "Search profile" input
- "More" button
- "Report" button
- Photo
- Title
- Description
- "Subscribe" button
- "Add event" button
- "Artist" button
- "Organizer" button
- "Venue" button
- "Upcoming" button
- "Past" button
- "Share" button
- "Ask locals" button
- "Instagram" button
- "Telegram" button
- "Twitter" button
- "Facebook" button
- Language switcher

**Comment by razbakov** [comment]
Duplicates #73
